-- [V] 시퀀스 : 순차번호 생성기. 인위적인 PK 사용용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1   -- 1부터 시작(기본값)
    INCREMENT BY 1 -- 1씩 증가(기본값)
    MAXVALUE 9999  -- 최대값
    MINVALUE 1
    NOCACHE
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 생성
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 시퀀스 현재값

-- EX. FRIEND테이블 : NO숫3-PK, NAME문20, TEL문20, ADDRESS문200, LAST_MODIFY날
DROP SEQUENCE FRIEND_NO_SEQ;
CREATE SEQUENCE FRIEND_NO_SEQ MAXVALUE 999 NOCACHE NOCYCLE;
CREATE TABLE FRIEND(
    NO   NUMBER(3)    PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    TEL  VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(200),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_NO_SEQ.NEXTVAL, '홍길동', NULL, '관악구 신림동');
SELECT * FROM FRIEND;
INSERT INTO FRIEND VALUES (friend_no_seq.nextval, '성춘향', '010-9999-9999', '남원', SYSDATE);
SELECT * FROM FRIEND;

-- ※※※ QUIZ ※※※
-- 테이블 및 시퀀스 삭제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL CASCADE CONSTRAINTS;;
DROP SEQUENCE MEMBER_MNO_SQ;
-- 테이블 및 시퀀스 생성
CREATE TABLE MEMBER_LEVEL(
  LEVELNO NUMBER(1) PRIMARY KEY,
  LEVELNAME VARCHAR2(20) NOT NULL
);
CREATE TABLE MEMBER(
    mNO     NUMBER(4)    PRIMARY KEY,
    mNAME   VARCHAR2(20) NOT NULL,
    mPW     VARCHAR2(8)  NOT NULL,
    -- mPW     VARCHAR2(8)  CHECK(LENGTH(MPW) BETWEEN 1 AND 8),
    mEMAIL  VARCHAR2(30) UNIQUE,
    mPOINT  NUMBER(10)   DEFAULT 1000 CHECK(mPOINT>=0),
    mRDATE  DATE         DEFAULT SYSDATE,
    LEVELNO NUMBER(1)    REFERENCES MEMBER_LEVEL(LEVELNO) 
);
CREATE SEQUENCE MEMBER_MNO_SQ MAXVALUE 9999 NOCACHE NOCYCLE;
-- 데이터 입력
INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드');
SELECT * FROM MEMBER_LEVEL;
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, 0);
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mRDATE, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 
            TO_DATE('22/04/01','RR/MM/DD'), 1);
SELECT * FROM MEMBER;

-- 데이터 출력
SELECT MNO, MNAME, TO_CHAR(MRDATE, 'YYYY-MM-DD') mEMAIL, MPOINT POINT, LEVELNAME||'고객' LEVELNAME
  FROM MEMBER M, MEMBER_LEVEL L
  WHERE M.LEVELNO = L.LEVELNO;





